### PR TITLE
Add defun! variant of defmacro!

### PR DESCRIPTION
**Pull request by EuAndreh**
You think that's worth adding?

### CODE REVIEW

**Comment by EuAndreh** [comment]
Now one can write:
```lisp
(defmacro! my-macro (a b)
  (declare (ignore a)) 
    ...)
```
... and get the expected behaviour, with or without docstrings.

**Comment by PuercoPop** [comment]
May I suggest `alexandria:parse-body` a less concrete way to extract declarations and docstrings?

**Comment by EuAndreh** [comment]
Nice tip @PuercoPop  =]

**Comment by thephoeron** [comment]
@EuAndreh: Before we merge in this pull request, can you add some tests for the new forms?

**Comment by EuAndreh** [comment]
Sure. I'll do it tonight, as soon as I get home.

**Comment by EuAndreh** [comment]
Is that what you had in mind? Do you suggest adding some more things?

**Comment by EuAndreh** [comment]
Now one can test with `(asdf:test-system :let-over-lambda)`.

**Comment by thephoeron** [comment]
Nice! thanks

**Pull request merged**
